[package]
name = "fpgrep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = { version = "4.1.8", features = ["derive"] }
is-terminal = "0.4.5"
log = "0.4.17"
regex = "1.7.1"
